### ISSUE TITLE
RemovedInDjango19Warning when categories app is not included in INSTALLED_APPS

### ISSUE THREAD

**Issue by miceno** [jazzband/django-categories#111]
As per the [documentation](http://django-categories.readthedocs.org/en/latest/installation.html#to-only-subclass-categorybase) to use `CategoryBase` class only, there is no need to include `categories` application on the INSTALLED_APPS. Thus, in that case, a warning shows:

```
2016-03-03 11:02:19,581 [WARNING] py.warnings: /py-new/lib/python2.7/site-packages/categories/models.py:128: 
RemovedInDjango19Warning: Model class categories.models.CategoryRelation doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
```

The environment is:

```
SO: Mac OS X
Python version: 2.7.10
Django-categories version: 1.4
Django version: 1.8.10
```

**Comment by epicserve** [comment]
@miceno, Sounds like the documentation needs to be changed, to say that you need to add 'categories' in INSTALLED_APPS. Want to make a PR?

**Comment by ratmcarlo** [comment]
I am facing the same problme of the OP.

I tried to add also 'categories' in INSTALLED_APPS, and I got this error:

```
[~/prj/fuzzic] $ python manage.py migrate
/home/carloratm/prj/fuzzic/items/views.py:11: RemovedInDjango110Warning: `items.views.ItemAddView.get_form` method must define a default value for its `form_class` argument.
  class ItemAddView(generic.CreateView):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/carloratm/.virtualenvs/env_fuzzic/lib/python2.7/site-packages/categories/migrations/0003_auto__add_field_category_thumbnail.py", line 3, in <module>
    from south.db import db
ImportError: No module named south.db
```

Environment is:

```
Linux
Python 2.7.11
django-categories==1.4
Django==1.9.2
```

**Comment by epicserve** [comment]
I'm puzzled. I have no idea how you could be using 1.4 because there is no file categories/migrations/0003_auto__add_field_category_thumbnail.py in version 1.4. Maybe uninstall your django-categories and then re-install.

**Comment by ratmcarlo** [comment]
I think the whl is not updated.
If I install django-categories with ``--no-use-wheel`` option, it works perfectly.

Here are the migrations from the whl archive: 

```
[/tmp] $ wget --quiet --no-verbose https://pypi.python.org/packages/2.7/d/django-categories/django_categories-1.4-py2-none-any.whl#md5=5969a67ea06ec9df03fc19d0e4ac3023
[/tmp] $ unzip -qq django_categories-1.4-py2-none-any.whl
[/tmp] $ ls categories/migrations/
total 20K
-rw-r--r-- 1 carloratm 3.4K 17:21 0001_initial.py
-rw-r--r-- 1 carloratm 3.1K 06:28 0002_auto__add_field_category_alternate_title__add_field_category_descripti.py
-rw-r--r-- 1 carloratm 2.3K 06:28 0003_auto__add_field_category_thumbnail.py
-rw-r--r-- 1 carloratm 3.2K 06:28 0004_auto__add_field_category_thumbnail_width__add_field_category_thumbnail.py
-rw-r--r-- 1 carloratm 2.7K 08:15 0005_auto__add_field_category_alternate_url.py
-rw-r--r-- 1 carloratm    0 06:28 __init__.py
```

**Comment by epicserve** [comment]
It could be that the Python 3 wheel is correct but the Python 2 version, isn't. I've made a note that I need to get that fixed.

**Comment by epicserve** [comment]
@ratmcarlo I just created a new release 1.4.1, can you check and make sure it's fixed. Also I updated the 1.4.0 and removed the py2 wheel, because the py3 wheel is universal. If you want to try installing 1.4.0 again make sure you ignore your cache using `pip install django-categories==1.4.0 --no-cache-dir`.

**Comment by PetrDlouhy** [comment]
This issue seems to refer to very old version of Django/django-categories. I am closing it. Please reopen if it is still relevant to the currently supported version of Django or newest version `2.0.0` of `django-categories`.
