### ISSUE TITLE
Apps aren't loaded. error in Django 1.9

### ISSUE THREAD

**Issue by corpulent** [jazzband/django-categories#118]
I installed using `pip install django-categories`.

Running Django 1.9,  django-mptt 0.8.4.

```
root@8c2d6b566d53:/# python /app/backend/manage.py runserver 0.0.0.0:9001
Traceback (most recent call last):
  File "/app/backend/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by PetrDlouhy** [comment]
This issue seems to refer to very old version of Django/django-categories. I am closing it. Please reopen if it is still relevant to the currently supported version of Django or newest version `2.0.0` of `django-categories`.
